import '@assets/main.css';
import 'keen-slider/keen-slider.min.css';
import { UiProvider } from '@components/ui/context';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <UiProvider>{children}</UiProvider>
            </body>
        </html>
    );
}
